# Generated by scripts/homebrew-formula.ts in colevels/tabbrew-cli; do not edit by hand.
class Tabbrew < Formula
  desc "Manage Chrome tabs, windows and tab groups from the terminal"
  homepage "https://github.com/colevels/tabbrew-cli"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/colevels/tabbrew-cli/releases/download/v0.9.9/tabbrew-darwin-arm64"
      sha256 "21ac9f4da24aaec0db3eed661052e912557dccc8b280ad2c6a697b21d36930ed"
    end
    on_intel do
      url "https://github.com/colevels/tabbrew-cli/releases/download/v0.9.9/tabbrew-darwin-x64"
      sha256 "2a357a382bbc59a8c5974a6c1f421d82bef481642ef835b08191da1516c42479"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/colevels/tabbrew-cli/releases/download/v0.9.9/tabbrew-linux-arm64"
      sha256 "ee25a49267754017212699395db29c829c153002cd2ce5d96ed0df6d5c05c3da"
    end
    on_intel do
      url "https://github.com/colevels/tabbrew-cli/releases/download/v0.9.9/tabbrew-linux-x64"
      sha256 "606eaa9a9202e16ed66b501d25476281cc230dce665db2d5efcd79366aaa05a6"
    end
  end

  def install
    bin.install Dir["tabbrew-*"].first => "tabbrew"
  end

  def caveats
    <<~EOS
      Install the TabBrew extension from the Chrome Web Store:
        https://chromewebstore.google.com/detail/ikmpmkkcmhhnjmdiooekbhfmomcbefkf
      Then: tabbrew session start

      Upgrade with `brew upgrade tabbrew`; `tabbrew update` refuses Homebrew installs.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tabbrew --version")
  end
end
