# Generated by scripts/homebrew-formula.ts in colevels/tabbrew-cli; do not edit by hand.
class Tabbrew < Formula
  desc "Manage Chrome tabs, windows and tab groups from the terminal"
  homepage "https://github.com/colevels/tabbrew-cli"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/colevels/tabbrew-cli/releases/download/v0.9.12/tabbrew-darwin-arm64"
      sha256 "3733c02fca6489c277cca2b3a3e1b2ba083d0a7deef0819212ca33d383be4f48"
    end
    on_intel do
      url "https://github.com/colevels/tabbrew-cli/releases/download/v0.9.12/tabbrew-darwin-x64"
      sha256 "10e18820bd59c5161c5d413501f10aee128514ed438d9599dd1c0842f8cdae37"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/colevels/tabbrew-cli/releases/download/v0.9.12/tabbrew-linux-arm64"
      sha256 "e0f5b661b3580655f5663071c38ee45c56359d56203b6b4a1dd956f2c608dcac"
    end
    on_intel do
      url "https://github.com/colevels/tabbrew-cli/releases/download/v0.9.12/tabbrew-linux-x64"
      sha256 "0426a8c9054c41f5c70d2fa6e2bb9a63e77d6eee67530b41f2ca3567d6af4935"
    end
  end

  def install
    bin.install Dir["tabbrew-*"].first => "tabbrew"
  end

  def caveats
    <<~EOS
      Install the TabBrew extension from the Chrome Web Store:
        https://chromewebstore.google.com/detail/ikmpmkkcmhhnjmdiooekbhfmomcbefkf
      Then: tabbrew session start

      Upgrade with `brew upgrade tabbrew`; `tabbrew update` refuses Homebrew installs.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tabbrew --version")
  end
end
