# Generated by scripts/homebrew-formula.ts in colevels/tabbrew-cli; do not edit by hand.
class Tabbrew < Formula
  desc "Manage Chrome tabs, windows and tab groups from the terminal"
  homepage "https://github.com/colevels/tabbrew-cli"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/colevels/tabbrew-cli/releases/download/v0.9.10/tabbrew-darwin-arm64"
      sha256 "909755da84d574906111452fb31ef3b944a7847518bee1501d5e03c04d770510"
    end
    on_intel do
      url "https://github.com/colevels/tabbrew-cli/releases/download/v0.9.10/tabbrew-darwin-x64"
      sha256 "26728fab7f7c8e9692f86cbec09b623e1eeab73acff90ba4b3f560f954e5ade3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/colevels/tabbrew-cli/releases/download/v0.9.10/tabbrew-linux-arm64"
      sha256 "5db8fb9a654934a4b9bde49f72f335198d665fe15fafb73d73d36ccf93a35f3b"
    end
    on_intel do
      url "https://github.com/colevels/tabbrew-cli/releases/download/v0.9.10/tabbrew-linux-x64"
      sha256 "87c36a161aee99575c4ad4f1d742073955223311cc62ad8fe86452f45e0eb275"
    end
  end

  def install
    bin.install Dir["tabbrew-*"].first => "tabbrew"
  end

  def caveats
    <<~EOS
      Install the TabBrew extension from the Chrome Web Store:
        https://chromewebstore.google.com/detail/ikmpmkkcmhhnjmdiooekbhfmomcbefkf
      Then: tabbrew session start

      Upgrade with `brew upgrade tabbrew`; `tabbrew update` refuses Homebrew installs.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tabbrew --version")
  end
end
